"use client";

import { useState } from "react";
import { Sparkles, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

export function AiSideEffectSummary({ genericId }: { genericId: string }) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleExplain = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/explain-side-effects", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ genericId }),
      });
      const data = await res.json();
      if (res.ok) {
        setSummary(data.summary);
      } else {
        setError(data.error || "Failed to generate summary.");
      }
    } catch (err) {
      setError("An error occurred. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-purple-500/5 dark:bg-purple-500/10 border border-purple-500/20 rounded-xl p-5 mb-6 transition-colors duration-300">
      <div className="flex items-center justify-between gap-4">
        <h3 className="font-bold text-purple-700 dark:text-purple-300 text-sm flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-purple-600 dark:text-purple-400 animate-pulse" />
          <span>AI Simplified Explanation</span>
        </h3>
        {!summary && (
          <Button 
            onClick={handleExplain} 
            disabled={isLoading}
            variant="outline"
            className="h-8 text-xs font-semibold text-purple-700 dark:text-purple-300 border-purple-500/30 hover:bg-purple-500/10 dark:hover:bg-purple-500/20 bg-transparent transition-all duration-200"
          >
            {isLoading ? <Loader2 className="w-3.5 h-3.5 mr-1 animate-spin" /> : null}
            Explain Simply
          </Button>
        )}
      </div>
      
      {summary && (
        <div className="mt-3 text-sm text-purple-800 dark:text-purple-200 leading-relaxed font-medium animate-fade-in">
          {summary}
          <p className="text-[10px] text-purple-500 dark:text-purple-400 mt-2.5 uppercase tracking-wider font-bold">
            Generated by Google Gemini • Not medical advice
          </p>
        </div>
      )}
      
      {error && <p className="text-sm text-destructive mt-2 font-semibold">{error}</p>}
    </div>
  );
}
